# Form implementation generated from reading ui file 'e:\mindx\pta03\BASIC-TO-DO\gui\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 755)
        MainWindow.setStyleSheet("background: rgb(255, 229, 33)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 391, 61))
        self.widget.setStyleSheet("border: 4px solid rgb(255, 170, 0);\n"
"  border-radius: 20px;\n"
"background: solid rgb(255, 245, 190);\n"
"color: black")
        self.widget.setObjectName("widget")
        self.txt_tiltle = QtWidgets.QTextBrowser(parent=self.widget)
        self.txt_tiltle.setGeometry(QtCore.QRect(0, 0, 391, 61))
        self.txt_tiltle.setStyleSheet("color: rgb(255, 136, 0)")
        self.txt_tiltle.setObjectName("txt_tiltle")
        self.todoList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.todoList.setGeometry(QtCore.QRect(20, 110, 371, 601))
        self.todoList.setGridSize(QtCore.QSize(0, 100))
        self.todoList.setObjectName("todoList")
        self.btn_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(20, 70, 41, 41))
        self.btn_plus.setStyleSheet("  font-size: 40px;\n"
"color: black;\n"
"background: solid rgb(255, 234, 2);\n"
"border: 4px solid rgb(255, 170, 0);\n"
"  border-radius: 20px;\n"
"  text-align: center;\n"
"")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_plus.raise_()
        self.widget.raise_()
        self.todoList.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_tiltle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">BASIC TO DO LIST</span></p></body></html>"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
